from typing import Any

from pydantic import BaseModel, Field, field_validator

class SearchPlan(BaseModel):
    """Schema for the search plan generated by the planner stage."""

    entity_type: str = Field(description="What kind of entities we're finding, e.g. 'AI startup', 'pizza restaurant'")
    schema_fields: list[str] = Field(description="Ordered list of attribute names to extract for each entity")
    search_queries: list[str] = Field(description="4-5 targeted web search queries")
    field_synonyms: dict[str, list[str]] = {}

class SourcedValue(BaseModel):
    """An extracted value coupled with its source URL and verbatim snippet."""

    value: Any
    source_url: str
    source_snippet: str = ""

    @field_validator("source_snippet", mode="before")
    @classmethod
    def coerce_none(cls, v):
        """Coerces None to empty string for source_snippet."""
        return v if isinstance(v, str) else ""

class Entity(BaseModel):
    """A named entity mapping extracted attributes to their sourced values."""

    name: str
    attributes: dict[str, SourcedValue]
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)

class SearchResult(BaseModel):
    """A single raw web search result output before scraping."""

    url: str
    title: str
    snippet: str

class ScrapedPage(BaseModel):
    """A scraped web page containing content chunks partitioned by HTML headers."""

    url: str
    title: str
    content: str
    structure_map: dict[str, str] = {}
    chunks: dict[str, str] = {}
    error: str | None = None

class FinalTable(BaseModel):
    """The final structured output table containing deduplicated entities and tracking metadata."""

    query: str
    entity_type: str
    schema_fields: list[str]
    entities: list[Entity]
    search_queries_used: list[str]
    sources: list[str]